[package]
name = "serde_list"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1", default-features = false }
serde_json = "1"
serde_list_macro = { path = "../serde_list_macro" }

[dev-dependencies]
serde = { version = "1", features = ["derive"] }
